version: "3.3"

services:
  app:
    image: python:latest
    ports:
      - "3000:8000"
    volumes:
      - $PWD:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - db
  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: testdb
